from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `activity` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `workflow_uid` CHAR(36) NOT NULL COMMENT '工作流UID',
    `uid` CHAR(36) NOT NULL UNIQUE,
    `name` VARCHAR(200) NOT NULL COMMENT '名称',
    `input` JSON NOT NULL COMMENT '输入参数',
    `output` JSON NOT NULL COMMENT '输出参数',
    `retry_count` INT NOT NULL COMMENT '失败重试次数' DEFAULT 0,
    `execute_params` JSON NOT NULL COMMENT '额外的 Celery 执行参数，覆盖默认值',
    `status` VARCHAR(9) NOT NULL COMMENT '状态' DEFAULT 'pending',
    `started_at` DATETIME(6) COMMENT '开始执行时间',
    `completed_at` DATETIME(6) COMMENT '完成时间',
    `error_message` LONGTEXT COMMENT '错误信息',
    `stack_trace` LONGTEXT COMMENT '错误堆栈跟踪',
    `canceled_at` DATETIME(6) COMMENT '取消时间',
    `celery_task_id` VARCHAR(255) COMMENT 'Celery 任务ID, direct执行模式下为空',
    UNIQUE KEY `uid_activity_workflo_0e4b51` (`workflow_uid`, `name`),
    KEY `idx_activity_created_5a6493` (`created_at`),
    KEY `idx_activity_workflo_fd04b5` (`workflow_uid`),
    KEY `idx_activity_status_6357fc` (`status`),
    KEY `idx_activity_celery__4333c8` (`celery_task_id`)
) CHARACTER SET utf8mb4 COMMENT='工作流活动表';
CREATE TABLE IF NOT EXISTS `conversation_memory` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `uid` CHAR(36) NOT NULL UNIQUE COMMENT '会话唯一标识',
    `session_id` VARCHAR(255) NOT NULL COMMENT '会话ID',
    `user_id` CHAR(36) COMMENT '用户ID',
    `agent_type` VARCHAR(50) NOT NULL COMMENT 'Agent类型',
    `messages` JSON NOT NULL COMMENT '对话历史消息列表',
    `agent_config` JSON NOT NULL COMMENT 'Agent配置',
    `tags` JSON NOT NULL COMMENT '标签列表',
    `metadata` JSON NOT NULL COMMENT '其他元数据',
    `last_updated` DATETIME(6) NOT NULL COMMENT '最后更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    KEY `idx_conversatio_created_ee2458` (`created_at`),
    KEY `idx_conversatio_deleted_7aaa08` (`deleted_at`),
    KEY `idx_conversatio_session_7b1e3f` (`session_id`),
    KEY `idx_conversatio_user_id_227072` (`user_id`),
    KEY `idx_conversatio_agent_t_aaa01d` (`agent_type`),
    KEY `idx_conversatio_last_up_3fd9c6` (`last_updated`)
) CHARACTER SET utf8mb4 COMMENT='对话记忆表';
CREATE TABLE IF NOT EXISTS `embedding_model_config` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `name` VARCHAR(100) NOT NULL UNIQUE COMMENT '配置名称',
    `type` VARCHAR(6) NOT NULL COMMENT '模型类型',
    `model_name` VARCHAR(255) NOT NULL COMMENT '模型标识符',
    `api_key` VARCHAR(500) COMMENT 'API密钥',
    `base_url` VARCHAR(500) COMMENT 'API基础URL',
    `dimension` INT NOT NULL COMMENT '向量维度',
    `max_chunk_length` INT NOT NULL COMMENT '单条chunk最大长度' DEFAULT 8192,
    `batch_size` INT NOT NULL COMMENT '批处理大小' DEFAULT 100,
    `max_retries` INT NOT NULL COMMENT '最大重试次数' DEFAULT 3,
    `timeout` INT NOT NULL COMMENT '请求超时时间(秒)' DEFAULT 60,
    `rate_limit` INT NOT NULL COMMENT '每分钟最大请求数(0=无限制)' DEFAULT 60,
    `extra_config` JSON NOT NULL COMMENT 'provider特定扩展配置',
    `is_enabled` BOOL NOT NULL COMMENT '是否启用' DEFAULT 1,
    `is_default` BOOL NOT NULL COMMENT '是否默认配置' DEFAULT 0,
    `description` LONGTEXT NOT NULL COMMENT '描述信息',
    KEY `idx_embedding_m_created_9e170e` (`created_at`),
    KEY `idx_embedding_m_deleted_496ead` (`deleted_at`),
    KEY `idx_embedding_m_is_enab_d158c4` (`is_enabled`),
    KEY `idx_embedding_m_is_defa_d46056` (`is_default`),
    KEY `idx_embedding_m_type_491b8f` (`type`)
) CHARACTER SET utf8mb4 COMMENT='Embedding模型配置表';
CREATE TABLE IF NOT EXISTS `collection` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `name` VARCHAR(100) NOT NULL COMMENT '集合名称',
    `description` LONGTEXT COMMENT '描述',
    `user_id` CHAR(36) COMMENT '用户ID',
    `tenant_id` CHAR(36) COMMENT '租户ID',
    `role_id` CHAR(36) COMMENT '角色ID',
    `is_public` BOOL NOT NULL COMMENT '是否公开' DEFAULT 0,
    `is_temp` BOOL NOT NULL COMMENT '是否临时' DEFAULT 0,
    `is_external` BOOL NOT NULL COMMENT '是否外部' DEFAULT 0,
    `workflow_template` JSON NOT NULL COMMENT '默认DAG工作流模版',
    `external_config` JSON NOT NULL COMMENT '外部知识库配置, 占位后续扩展',
    `embedding_model_config_id` BIGINT COMMENT '关联嵌入模型',
    UNIQUE KEY `uid_collection_user_id_a5fa2b` (`user_id`, `name`),
    CONSTRAINT `fk_collecti_embeddin_fe4e9165` FOREIGN KEY (`embedding_model_config_id`) REFERENCES `embedding_model_config` (`id`) ON DELETE RESTRICT,
    KEY `idx_collection_created_385054` (`created_at`),
    KEY `idx_collection_deleted_d4b7b6` (`deleted_at`)
) CHARACTER SET utf8mb4 COMMENT='文件集合表';
CREATE TABLE IF NOT EXISTS `file_source` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `name` VARCHAR(100) NOT NULL COMMENT '文件源名称',
    `type` VARCHAR(10) NOT NULL COMMENT '文件源类型',
    `access_key` VARCHAR(500) COMMENT '访问密钥',
    `secret_key` VARCHAR(500) COMMENT '密钥（加密存储）',
    `storage_location` VARCHAR(1000) COMMENT '存储位置  - type=local_file: 本地文件路径（如 /data/documents）  - type=s3/minio/aliyun_oss: 存储桶名称（如 my-bucket）',
    `endpoint` VARCHAR(500) COMMENT '服务端点URL',
    `region` VARCHAR(100) COMMENT '区域/地域',
    `use_ssl` BOOL NOT NULL COMMENT '是否使用SSL/TLS' DEFAULT 1,
    `verify_ssl` BOOL NOT NULL COMMENT '是否验证SSL证书' DEFAULT 1,
    `timeout` INT NOT NULL COMMENT '连接/读取超时时间(秒)' DEFAULT 30,
    `max_retries` INT NOT NULL COMMENT '最大重试次数' DEFAULT 3,
    `concurrent_limit` INT NOT NULL COMMENT '并发限制' DEFAULT 10,
    `max_connections` INT NOT NULL COMMENT '最大连接数(连接池)' DEFAULT 100,
    `is_enabled` BOOL NOT NULL COMMENT '是否启用' DEFAULT 1,
    `is_default` BOOL NOT NULL COMMENT '是否默认' DEFAULT 0,
    `user_id` CHAR(36) COMMENT '用户ID, 为空时表示公共',
    `description` LONGTEXT NOT NULL COMMENT '描述信息',
    `extra_config` JSON NOT NULL COMMENT 'Provider特定扩展配置（JSON格式）',
    UNIQUE KEY `uid_file_source_name_80971a` (`name`, `deleted_at`),
    KEY `idx_file_source_created_05ed79` (`created_at`),
    KEY `idx_file_source_deleted_a0dbf6` (`deleted_at`),
    KEY `idx_file_source_type_0a0019` (`type`, `is_enabled`),
    KEY `idx_file_source_is_defa_df421e` (`is_default`, `is_enabled`)
) CHARACTER SET utf8mb4 COMMENT='文件源配置表';
CREATE TABLE IF NOT EXISTS `document` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `uri` VARCHAR(1000) NOT NULL COMMENT '文件唯一标识（本地为绝对路径）',
    `parsed_uri` VARCHAR(1000) COMMENT '解析后的文件唯一标识',
    `file_name` VARCHAR(255) NOT NULL COMMENT '文件名',
    `display_name` VARCHAR(255) NOT NULL COMMENT '显示名称',
    `extension` VARCHAR(50) NOT NULL COMMENT '文件扩展名',
    `file_size` BIGINT COMMENT '文件大小(字节)',
    `source_last_modified` DATETIME(6) COMMENT '文件源最后修改时间',
    `source_version_key` VARCHAR(100) COMMENT '文件源版本标识',
    `is_deleted_in_source` BOOL NOT NULL COMMENT '文件是否在源中被删除' DEFAULT 0,
    `source_meta` JSON COMMENT '文件源元数据（JSON格式）',
    `short_summary` VARCHAR(255) COMMENT '文件摘要',
    `long_summary` LONGTEXT COMMENT '文件详细摘要',
    `status` VARCHAR(11) NOT NULL COMMENT '文件状态',
    `current_workflow_uid` CHAR(36) COMMENT '当前关联的最新工作流UID',
    `config_flag` SMALLINT NOT NULL COMMENT '配置标志' DEFAULT 0,
    `workflow_template` JSON NOT NULL COMMENT 'DAG工作流模版',
    `collection_id` BIGINT NOT NULL COMMENT '关联集合',
    `file_source_id` BIGINT NOT NULL COMMENT '关联文件源',
    UNIQUE KEY `uid_document_collect_815685` (`collection_id`, `uri`, `deleted_at`),
    UNIQUE KEY `uid_document_collect_d93e8a` (`collection_id`, `file_name`, `deleted_at`),
    CONSTRAINT `fk_document_collecti_6805aced` FOREIGN KEY (`collection_id`) REFERENCES `collection` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_document_file_sou_77594071` FOREIGN KEY (`file_source_id`) REFERENCES `file_source` (`id`) ON DELETE RESTRICT,
    KEY `idx_document_created_b6cfaa` (`created_at`),
    KEY `idx_document_deleted_b64b7d` (`deleted_at`),
    KEY `idx_document_collect_2893ec` (`collection_id`),
    KEY `idx_document_collect_e0dffb` (`collection_id`, `status`),
    KEY `idx_document_collect_34bbbd` (`collection_id`, `extension`),
    KEY `idx_document_file_so_b54b49` (`file_source_id`)
) CHARACTER SET utf8mb4 COMMENT='文件记录表';
CREATE TABLE IF NOT EXISTS `document_chunk` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `content` LONGTEXT NOT NULL COMMENT '切块内容',
    `pages` JSON NOT NULL COMMENT '切块页码列表',
    `min_page` SMALLINT NOT NULL COMMENT '最小页码',
    `max_page` SMALLINT NOT NULL COMMENT '最大页码',
    `start` JSON NOT NULL COMMENT '起始位置（页码+页内偏移）',
    `end` JSON NOT NULL COMMENT '结束位置（页码+页内偏移）',
    `overlap_start` JSON COMMENT '重叠起始位置（页码+页内偏移）',
    `overlap_end` JSON COMMENT '重叠结束位置（页码+页内偏移）',
    `metadata` JSON NOT NULL COMMENT '元数据',
    `document_id` BIGINT NOT NULL COMMENT '文档ID',
    CONSTRAINT `fk_document_document_c3048c62` FOREIGN KEY (`document_id`) REFERENCES `document` (`id`) ON DELETE CASCADE,
    KEY `idx_document_ch_created_832cef` (`created_at`),
    KEY `idx_document_ch_deleted_861940` (`deleted_at`),
    KEY `idx_document_ch_documen_6d4d6c` (`document_id`),
    KEY `idx_document_ch_documen_830978` (`document_id`, `min_page`),
    KEY `idx_document_ch_documen_95700d` (`document_id`, `max_page`)
) CHARACTER SET utf8mb4 COMMENT='文档切块记录表';
CREATE TABLE IF NOT EXISTS `document_gfaq` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `content` LONGTEXT COMMENT '相关文档内容块',
    `question` LONGTEXT COMMENT '问题',
    `answer` LONGTEXT COMMENT '答案',
    `manual_add` BOOL NOT NULL COMMENT '是否手动添加' DEFAULT 0,
    `enabled` BOOL NOT NULL COMMENT '是否启用' DEFAULT 1,
    `document_id` BIGINT NOT NULL COMMENT '文档',
    CONSTRAINT `fk_document_document_6ae6cb1d` FOREIGN KEY (`document_id`) REFERENCES `document` (`id`) ON DELETE CASCADE,
    KEY `idx_document_gf_created_42c227` (`created_at`),
    KEY `idx_document_gf_deleted_8441f3` (`deleted_at`),
    KEY `idx_document_gf_documen_813344` (`document_id`),
    KEY `idx_document_gf_documen_64cc9a` (`document_id`, `enabled`)
) CHARACTER SET utf8mb4 COMMENT='文档生成FAQ表';
CREATE TABLE IF NOT EXISTS `document_page` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `page_number` SMALLINT NOT NULL COMMENT '页码',
    `content` LONGTEXT NOT NULL COMMENT '页面内容，当只有一页的时候content太长可以不存，但是必须要有page记录，content可以从parsed_uri获取',
    `tables` JSON NOT NULL COMMENT '页面表格信息',
    `images` JSON NOT NULL COMMENT '页面图片信息, list[keys]',
    `metadata` JSON NOT NULL COMMENT '页面元数据',
    `document_id` BIGINT NOT NULL COMMENT '文档ID',
    CONSTRAINT `fk_document_document_0e602c07` FOREIGN KEY (`document_id`) REFERENCES `document` (`id`) ON DELETE CASCADE,
    KEY `idx_document_pa_created_aa6a2c` (`created_at`),
    KEY `idx_document_pa_deleted_b9b7ee` (`deleted_at`),
    KEY `idx_document_pa_documen_0755d0` (`document_id`),
    KEY `idx_document_pa_documen_5fe339` (`document_id`, `page_number`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `indexing_backend_config` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `name` VARCHAR(100) NOT NULL UNIQUE COMMENT '配置名称',
    `type` VARCHAR(13) NOT NULL COMMENT '后端类型',
    `host` VARCHAR(255) COMMENT '主机地址',
    `port` INT COMMENT '端口号',
    `username` VARCHAR(255) COMMENT '用户名',
    `password` VARCHAR(500) COMMENT '密码（加密）',
    `use_ssl` BOOL NOT NULL COMMENT '是否使用SSL/TLS' DEFAULT 1,
    `verify_ssl` BOOL NOT NULL COMMENT '是否验证SSL证书' DEFAULT 1,
    `timeout` INT NOT NULL COMMENT '连接超时时间(秒)' DEFAULT 30,
    `max_retries` INT NOT NULL COMMENT '最大重试次数' DEFAULT 3,
    `max_connections` INT NOT NULL COMMENT '最大连接数(连接池)' DEFAULT 100,
    `extra_config` JSON NOT NULL COMMENT 'Provider特定扩展配置',
    `is_enabled` BOOL NOT NULL COMMENT '是否启用' DEFAULT 1,
    `is_default` BOOL NOT NULL COMMENT '是否默认配置' DEFAULT 0,
    `description` LONGTEXT NOT NULL COMMENT '描述信息',
    KEY `idx_indexing_ba_created_840754` (`created_at`),
    KEY `idx_indexing_ba_deleted_b9dd20` (`deleted_at`),
    KEY `idx_indexing_ba_type_0a4885` (`type`, `is_enabled`),
    KEY `idx_indexing_ba_is_defa_73e737` (`is_default`, `is_enabled`)
) CHARACTER SET utf8mb4 COMMENT='索引后端配置表';
CREATE TABLE IF NOT EXISTS `llm_model_config` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `name` VARCHAR(100) NOT NULL UNIQUE COMMENT '配置名称',
    `type` VARCHAR(12) NOT NULL COMMENT '模型类型',
    `model_name` VARCHAR(255) NOT NULL COMMENT '模型标识符',
    `api_key` VARCHAR(500) COMMENT 'API密钥（加密）',
    `base_url` VARCHAR(500) COMMENT 'API基础URL',
    `max_tokens` INT NOT NULL COMMENT '最大token数（输入+输出）' DEFAULT 4096,
    `supports_chat` BOOL NOT NULL COMMENT '支持对话模式' DEFAULT 1,
    `supports_completion` BOOL NOT NULL COMMENT '支持补全模式' DEFAULT 0,
    `supports_streaming` BOOL NOT NULL COMMENT '支持流式输出' DEFAULT 1,
    `supports_function_calling` BOOL NOT NULL COMMENT '支持函数调用' DEFAULT 0,
    `supports_vision` BOOL NOT NULL COMMENT '支持视觉/图像' DEFAULT 0,
    `default_temperature` DOUBLE NOT NULL COMMENT '默认温度参数' DEFAULT 0.7,
    `default_top_p` DOUBLE NOT NULL COMMENT '默认top_p' DEFAULT 1,
    `max_retries` INT NOT NULL COMMENT '最大重试次数' DEFAULT 3,
    `timeout` INT NOT NULL COMMENT '请求超时时间(秒)' DEFAULT 60,
    `extra_config` JSON NOT NULL COMMENT 'provider特定扩展配置',
    `is_enabled` BOOL NOT NULL COMMENT '是否启用' DEFAULT 1,
    `is_default` BOOL NOT NULL COMMENT '是否默认配置' DEFAULT 0,
    `description` LONGTEXT NOT NULL COMMENT '描述信息',
    KEY `idx_llm_model_c_created_483236` (`created_at`),
    KEY `idx_llm_model_c_deleted_25ea9c` (`deleted_at`),
    KEY `idx_llm_model_c_is_enab_578b90` (`is_enabled`),
    KEY `idx_llm_model_c_is_defa_011321` (`is_default`),
    KEY `idx_llm_model_c_type_ab2c6f` (`type`)
) CHARACTER SET utf8mb4 COMMENT='LLM模型配置表';
CREATE TABLE IF NOT EXISTS `workflow` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` BIGINT COMMENT '删除时间',
    `uid` CHAR(36) NOT NULL UNIQUE COMMENT '幂等性唯一标识',
    `config` JSON NOT NULL COMMENT '工作流配置（DAG图结构，支持YAML/JSON格式）, {content: vv}',
    `config_format` VARCHAR(4) NOT NULL COMMENT '配置格式（yaml/json/python）' DEFAULT 'yaml',
    `status` VARCHAR(9) NOT NULL COMMENT '工作流状态' DEFAULT 'pending',
    `started_at` DATETIME(6) COMMENT '开始执行时间',
    `completed_at` DATETIME(6) COMMENT '完成时间',
    `canceled_at` DATETIME(6) COMMENT '是否被取消',
    KEY `idx_workflow_created_c2a8eb` (`created_at`),
    KEY `idx_workflow_deleted_d3d134` (`deleted_at`)
) CHARACTER SET utf8mb4 COMMENT='工作流定义表';"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
